name: "Setup Test Environment"
description: "Sets up Node.js, installs dependencies, and sets env vars"
inputs:
  node-version:
    description: "Node.js version to install"
    required: true
    default: "20"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Set environment variable
      run: echo "TEST_ENV=true" >> $GITHUB_ENV
