name: 'Setup Test Environment'
description: 'Install dependencies and prepare testing environment'

runs:
  using: "composite"
  steps:
    - name: Install Node dependencies
      run: npm install
      shell: bash

    - name: Install Jest
      run: npm install --save-dev jest
      shell: bash
