name: Task 3 - Integration Test on Static Site Container

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: ghcr.io/${{ github.repository }}:latest
        ports:
          - 8080:80
        options: >-
          --health-cmd="wget --spider -q http://localhost:80"
          --health-interval=5s
          --health-retries=5
          --health-timeout=2s
          --health-start-period=5s

    steps:
      - name: Wait for container to be healthy
        run: sleep 10

      - name: Test HTTP status code
        run: |
          status_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080)
          echo "Status code: $status_code"
          if [ "$status_code" -ne 200 ]; then
            echo "Site is not up!"
            exit 1
          fi
