name: Task 4 - Run Tests with Custom Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Environment and Run Tests
        uses: ./.github/custom-action/setup-test-env
